config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :orders
  resources :line_items
  resources :carts
  devise_for :users
  get "static_pages/home"
  get "static_pages/appetizer"
  get "static_pages/dishes"
  get "static_pages/desserts"
  root "static_pages#home"
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = []
    if session[:cart_id] != nil
      @carts << Cart.find_by_id(session[:cart_id])
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div class="row">
  <div class="col-sm-2 left-show-cart"></div>
  <div class="col-sm-8 container-cart">
    <div class="cart-text-1">Giỏ Hàng</div>
    <hr class="hr-cart">
    <div class="rơw">
      <div class="col-sm-6">
        <div class="cart-text-2">Sản phẩm</div>
        <hr class="hr-cart">
        <% @cart.line_items.each do |a| %>
          <span class="cart-product-image"><%= link_to image_tag(a.product.image.url) %></span>
          <span class="cart-product-name"><%= a.product.name %></span>
          <hr class="hr-cart">
        <% end %>
      </div>
      <div class="col-sm-2">
        <div class="cart-text-2">Giá</div>
        <hr class="hr-cart">
        <% @cart.line_items.each do |a| %>
        <div style="height: 90px;">
          <span class="cart-product-name"><%= a.product.price %></span>
        </div>
          <hr class="hr-cart">
        <% end %>
      </div>
      <div class="col-sm-4">
        <div class="cart-text-2">Số lượng</div>
        <hr class="hr-cart">
        <% @cart.line_items.each do |a| %>
        <div style="height: 90px;">
          <span class="cart-product-name"><%= a.quantity %></span>
        </div>
          <hr class="hr-cart">
        <% end %>
      </div>
    </div>
    <div>
      <span class="total">Tổng cộng: </span>
      <span class="total-2"><%= number_to_currency(@cart.total_price) %></span>
      <hr class="hr-cart">
    </div>
    <div class="empty-cart">
      <div class="bottom-div-product">
      <div id="custom">
        <%= button_to 'Empty cart',
          @cart,
          :method => :delete,
          data: {:confirm => 'Are you sure?'} %>
      </div>
      </div>
      <div id="custom-2"><%= button_to 'Mua Hàng',
              new_order_path,
              :method => :get %></div>
      </div>
    </div>
<div class="col-sm-2 left-show-cart"></div>
  </div>