config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :orders
  resources :line_items
  resources :carts
  devise_for :users
  get "static_pages/home"
  get "static_pages/appetizer"
  get "static_pages/dishes"
  get "static_pages/desserts"
  root "static_pages#home"
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="row">
    <div class="col-sm-3 img-footer"><img src="https://lirp-cdn.multiscreensite.com/7014fe0e/dms3rep/multi/opt/mua-w-960w.png" id="1046860240" class="" data-dm-image-path="https://irp-cdn.multiscreensite.com/7014fe0e/dms3rep/multi/mua-w.png" onerror="handleImageLoadError(this)"></div>
    <div class="col-sm-5">
      <p id="contact-us">Contact Us</p>
      <p id="addess">761 S MacArthur Blvd. #121 Coppell, TX 75019
(972) 745 3377</p>
    </div>
    <div class="col-sm-4">
      <p id="contact-us">Opening Hours</p>
      <div>
        <span id="contact-us">Mon - Fri</span>
        <span>
          <span id="font-default">11:00 am - 2:30 pm</span>
          <div id="font-default">4:30 pm - 9:30 pm</div>
        </span>
        <span id="contact-us">Sat - Sun</span>
        <span id="font-default">
          4:30 pm - 9:30 pm
        </span>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header-on-top">
  <span id="order-in-header-on-top">ONLINE ORDER & FREE DELIVERY AVAILABLE!</span>
  <span id="order-now-in-header-on-top"><%= link_to "ORDER NOW!", "#" %></span>
</div>
<div class="header-below-on-top">
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", "#", {'data-toggle' => 'modal', 'data-target' => '#myModal'} %></li>
    <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">About</h4>
        </div>
        <div class="modal-body">
          <div class="col-sm-6 image-about">
            <img src="https://lirp-cdn.multiscreensite.com/7014fe0e/dms3rep/multi/opt/mua_name-400w.png">
          </div>
          <div class="col-sm-6 p-about">
            <p>Our name derives from a Japanese character describing the experience of losing oneself and forgetting the world. The moment you taste the unbelievably fresh and dynamic flavors of our sushi, sashimi and rolls everything else melts away. <br>At Mua Sushi we offer meals of excellent quality and invite you to try our delicious food.<br>The key to our success is simple: providing quality consistent food that taste great every single time. We pride ourselves on serving our customers delicious genuine dishes like: Sushi, Japanese Food
            <br>Eat delicious food. Grab a drink. But most of all, relax! We thank you from the bottom of our hearts for your continued support.</p>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <span class="dropdown">
    <li class="dropdown-toggle" type="button" data-toggle="dropdown"><%= link_to "Menu", "#" %>
    <span class="caret"></span></li>
    <ul class="dropdown-menu">
      <li><%= link_to "Appetizer", static_pages_appetizer_path %></li>
      <li><%= link_to "Main Dishes", static_pages_dishes_path %></li>
      <li><%= link_to "Desserts", static_pages_desserts_path %></li>
    </ul>
  </span>
    <li><img src="https://irp-cdn.multiscreensite.com/7014fe0e/dms3rep/multi/desktop/Mua-Sushi_LOGO.png"></li>
    <li id="order-now"><%= link_to "Order Now", "#" %></li>
      <% if user_signed_in? %>
        <span class="dropdown current-user">
          <li class="dropdown-toggle" type="button" data-toggle="dropdown"><%= link_to current_user.email, "#" %>
          <span class="caret"></span></li>
          <ul class="dropdown-menu">
            <li><%= link_to "Hồ sơ", "#" %></li>
            <li><%= link_to "Đăng xuất", destroy_user_session_path %></li>
          </ul>
        </span>
      <% else %>
        <li><%= link_to "Đăng kí", new_user_registration_path %></li>
        <li><%= link_to "Đăng nhập", user_session_path %></li>
      <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SushiAmazing</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>